source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.yintech.net:epmios/epmspecs.git'
source 'git@gitlab.yintech.net:dxios/dxspecs.git'
source 'git@gitlab.baidao.com:dxios/dxspecs.git'

target 'Sample' do
  # use_frameworks!
  pod 'LogInWindow', :path => '../../LogInWindow'
  pod 'EPMLogger'
end
