source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.yintech.net:epmios/epmspecs.git'
source 'git@gitlab.yintech.net:dxios/dxspecs.git'
source 'git@gitlab.baidao.com:dxios/dxspecs.git'

target 'Sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sample
  pod 'LogInWindow', :path => '../../LogInWindow'
  pod 'EPMLogger'
end
